name: core
description: "Core package for TrimFlow, containing models and shared interfaces."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.5
  build_runner: ^2.15.0
  json_serializable: ^6.13.2

flutter:
  uses-material-design: true
